### ISSUE TITLE
ValidatorWorker Logging

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#105]
We have many places which we log when something goes wrong. See the [JS implementation](https://github.com/AdExNetwork/adex-validator) for references where we need it.

Main questions we need to answer:
- [x] What logger will be used ([`slog`](https://github.com/slog-rs/slog))
- [x] What will be logged (see comments bellow with the tasks)

**Comment by elpiel** [comment]
SentryApi currently does not log the propagation of messages as the JS impl.

**Comment by elpiel** [comment]
- [ ] **Low** https://github.com/AdExNetwork/adex-validator-stack-rust/blob/89a2c1ed73/validator_worker/src/main.rs#L163-L166

    ```
    if let Err(e) = result {
        eprintln!("Failed to get channels {}", e);
        return Ok(());
    }
    ```

Logging is required instead of `eprintln!`.
Also on https://github.com/AdExNetwork/adex-validator-stack-rust/blob/89a2c1ed73/validator_worker/src/main.rs#L168 we can remove the `unwrap()` by using a `match` instead of `if let` which can improve readability and remove an unnecessary `unwrap()`.

- [ ] **Low** https://github.com/AdExNetwork/adex-validator-stack-rust/blob/89a2c1ed73/validator_worker/src/main.rs#L177-L179

    ```
    if let Err(e) = tick {
        eprintln!("An occurred while processing channels {}", e);
    }
    ```

    Logging instead `eprintln!`.

- [ ] **Low** https://github.com/AdExNetwork/adex-validator-stack-rust/blob/89a2c1ed73/validator_worker/src/main.rs#L182-L185

    ```
    eprintln!(
        "WARNING: channel limit cfg.MAX_CHANNELS={} reached",
        args.config.max_channels
    )
    ```

Logging instead `eprintln!`.

- [ ] __Low__ https://github.com/AdExNetwork/adex-validator-stack-rust/blob/89a2c1ed73/validator_worker/src/sentry_interface.rs#L174

    Missing Logging as in the JS impl.
    Should be noted we need to pass the logger, probably as an `Option<Logger>` and resolve the current `logging: bool`.

- [ ] __Low__ https://github.com/AdExNetwork/adex-validator-stack-rust/blob/89a2c1ed73/validator_worker/src/sentry_interface.rs#L202
    
    `handle_http_error` should also log, instead of `println!`.
    This will align the interface (although not entirely) to the JS impl.

**Comment by elpiel** [comment]
- [ ] `producer::tick` should also log the merging of events
