### ISSUE TITLE
Channel Middlewares

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#189]
### [JS impl](https://github.com/AdExNetwork/adex-validator/blob/05-stable/middlewares/channel.js) reference

- [x] channelLoad (channel_load) #198 
- [x] channelIfExists (channel_load) #198 
- [x] channelIfFind (private) (channel_load) #198 
- [x] channelIfActive  #198
