### ISSUE TITLE
ChannelSpec fields

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#24]
Add fields:
- [x] `title` added in #37
- [x] [`adUnits`](https://github.com/AdExNetwork/adex-validator-stack-rust/issues/28) added in #37
- [x] [`targeting`](https://github.com/AdExNetwork/adex-validator-stack-rust/issues/26) added in #37
- [x] `validators` ( should be an array of 2 validators - leader & follower) #53 
- [x] `withdrawPeriodStart` added in #37
- [x] `minPerImpression` added in #37
- [x] `maxPerImpression` added in #37
- [x] `minTargetingScore` added in #37
- [x] [`eventSubmission`](https://github.com/AdExNetwork/adex-validator-stack-rust/issues/27) added in #37
- [x] `nonce` added in #37
- [x] `created` added in #37
- [x] `activeFrom` added in #37

- [ ] update fixtures - still requires fixtures for AdUnit, EventSubmission and etc.
- [ ] Implement the `withdraw_period_start` restriction from the [channel validation in the JS implementaiton](https://github.com/AdExNetwork/adex-validator/blob/master/adapters/lib.js#L46) in the ChannelSpec deserialization (probably wrap the BigNum in a tuple struct and validate it there)

Postgres implementation:
- [x] should be a json blob inside Channel PR #42 
- [x] `validators` should be in the blob as an array PR #42

**Comment by elpiel** [comment]
No need for this anymore
