### ISSUE TITLE
Domain structs

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#29]
- [x] Channel ~(partially implemented, it still needs some field though)~
- [ ] ChannelSpec #24 (partially implemented, it still needs some fields though)
- [x] Validator
- [ ] AdUnit #28
- [x] TargetingTag #26
- [x] Validator Messages from [validator stack](https://github.com/AdExNetwork/adex-protocol/blob/master/components/validator-stack.md#validator-messages) #72 
- [ ] EventSubmition & EventSubmitionRule #27 
- [x] ~UserId trait/struct~ #36
