### ISSUE TITLE
AIP#31 Targeting rules engine

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#296]
# https://github.com/AdExNetwork/aips/issues/31
Part of AdExNetwork/adex-supermarket#9 

## Examples

https://github.com/AdExNetwork/aips/blob/master/examples/aip31.js

## Rust `eval` signature

```rust
enum Error {
    TypeError,
    UnknownVariable
}

fn eval(input: &Input, output: &mut Output, rule: &Rule) -> Result<Option<Value>, Error>
```

See #297 for the impl of Input/Output variables of https://github.com/AdExNetwork/aips/issues/31

### Values:
- [x] #297 `Bool(bool)`
- [x] #297 `Number(Number)`
- [x] #297 `String(String)`
- [x] #297 `Array(Vec<Value>)`
- [x] #297 `BigNum(BigNum)`

#### Math
> If a math function is invoked with numeric, but different types, it will try to cast all the arguments to a BigNumber
- [x] #297 `Div(Box<Rule>, Box<Rule>)`
  - [x] TODO: Make the casting change according to the AIP#31 new changes
- [x] Mul
- [x] Mod
- [x] Add
- [x] Sub
- [x] Max
- [x] Min

#### Variables
- [x] #297 `Get(String)`
  - [x] PR #325  `Get` should be applied to `Output` as well
- [x] #297 `Set(String, Box<Rule>)`

       > NOTE: rules that use variables that are only accessible on the AdView cannot change the price, since it's ultimately determined by the validator.

#### Syntax sugar
- [x] onlyShowIf
- [x] ~? setMul **`*=`**~ Not impled in JS or Rust atm
- [x] ~? setAdd **`+=`**~ Not impled in JS or Rust atm

#### Price helpers
- [x] #307 (PR #305 & PR #321 ) getPriceInUSD @simzzz 

  > getPriceInUSD will return the currently set price for a specific event, approximated in USD; this is useful for the ad slot rules, as it allows setting min CPM regardless of asset type

#### Logic
- [x] or
- [x] #297 `And(Box<Rule>, Box<Rule>)`
- [x] xor
- [x] not

#### Flow control
- [x] #297 `If(Box<Rule>, Box<Rule>)`
- [x] ifNot
- [x] ifElse
- [x] PR #305 do

#### Comparison
- [x] lt
- [x] lte
- [x] gt
- [x] gte
- [x] eq
- [x] neq
- [x] nin
- [x] in
- [x] #297 `Intersects(Box<Rule>, Box<Rule>)`
- [x] between

#### Reading from arrays
- [x] at

#### Strings
- [x] split
- [x] endsWith
- [x] startsWith

#### Type Cast
- [x] #297 `Bn(BigNum)`

  > (bn: casts a string to a BigNumber)
