### ISSUE TITLE
Channel List API endpoint

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#3]
Implement the Channel List API Endpoint:
https://github.com/AdExNetwork/adex-validator-stack-js/blob/master/routes/channel.js#L84

**Current status:** Some Channel data is returned.
**TODOs:**
- [x] ~Hydrate the rest of the information for the channel, i.e. ChannelSpecs and the Validators of the ChannelSpec.~ As we are skipping the PostgresRepository implementation and working with the MemoryRepository we don't need this for now.
- [x] Add `page` query parameter #21
- [x] Add `validator` query parameter for filtering channels that contain a specific validator #21
- [x] Fetch only channels that have `validUntil > now` #20 
- [x] Define a "CHANNELS_~FIND~**LIST**_LIMIT" for limit of channels per page (application configuration) #31 
- [x] `channel_list` Handler limit per page to which we can pass the application configuration value #21 
- [x] Filter options in `ChannelRepository::list` for `page`, `limit` & `valid_until_ge` #20 
- [x] Filter option in `ChannelRepository::list` for `validator` #22
- [x] Implement the `fromSql` & `toSql` for `BigNum` ( I've opened an [Issue in num-biging](https://github.com/rust-num/num-bigint/issues/94) if they are able to help me to implement the BigUint for postgres and how to represent it in the database, for now it will remain ~`u64`~ `String`)
