### ISSUE TITLE
AIP#31 `Event::UpdateTargeting` (`UPDATE_TARGETING`)

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#335]
`Sentry` is still missing some impl details that were already made in the JS Sentry.

Since the introduction of https://github.com/AdExNetwork/aips/issues/31 there is a new Event type that was added called `UPDATE_TARGETING`.

### TODO:
- [x] Add the new Event type
- [x] Update the channel
- [x] Apply the correct `access` restrictions in `sentry/src/access.rs`
- [x] Test additions in `access.rs`
- [ ] impl tests for the route
   **Note:** This is related to #319 since it's calling the `EventAggregator`
