### ISSUE TITLE
Re-think Targeting Input AIP#31

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#340]
There is a problem with the current `Input` for targeting. This is that while `Source` can serialize with proper `targeting::eval::Value`s, the `Map` (`HashMap<String, targeting::input::Value>`) can't since it's set by deserializing a Json value (`serde_json::Value`). This causes problems since using the `Map` as a base for e.g. `adview-manager` will result in loosing information about the values of the targeting input.

## Todos:

- [x] enable assertion of Targeting input in Supermarket - https://github.com/AdExNetwork/adex-supermarket/pull/29

https://github.com/AdExNetwork/adex-supermarket/blob/ca659b469da0bfe401e41f5fb47e27be0afeb3ad/src/units_for_slot_test.rs#L298-L299
- [x] Update Supermarket https://github.com/AdExNetwork/adex-supermarket/pull/29
- [x] Check Input variables for Supermarket from https://github.com/AdExNetwork/aips/issues/31
