### ISSUE TITLE
AIP #61: AdEx v5: significantly cheaper channels

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#377]
### Tracking issue
For the changes regarding [AIP#61: AdEx v5: significantly cheaper channels (full details here)](https://github.com/AdExNetwork/aips/issues/61)

### Change log
- [x] `Channel` & `Campaign` #382 (PRs: #383 )
- [x] `NewState` & `Accounting` #398 
- [x] Sentry
  - [x] API documentation #475 
    - [x] #443 
    - [x] #473 
    - [x] #524 
  - [x] Accounting & spenders #381 
  - [x] GET /v5/channel/:id/accounting #431  @simzzz 
  - [x] GET /v5/channel/:id/spender/:addr #391
  - [x] GET /v5/channel/:id/spender/all #392 
  - [x] POST /v5/channel/:id/spender/:addr #465 @simzzz 
    - [x] Change output to use SpenderResponse instead of just success: true #484 @simzzz 
  - [x] POST /v5/channel/:id/pay #477 @simzzz 
  Channel Payout with authentication of the spender.
  Withdrawals of advertiser funds - re-introduces the `PAY` event with a separate route
  - [x] GET /v5/channel/:id/get-leaf @simzzz (PR #544)
    from AIP#61:
    > add another helper route /get-leaf that is called like this: /get-leaf?spender=... or /get-leaf?earner=...; this will get the latest approved state (NewState/ApproveState pair), will find the given spender/earner in the balances tree, and produce a merkle proof for it; this is useful for the Platform to verify if a spender leaf really exists
    
    I've discussed this with Ivo, we will make spender/earner routes instead of using query parameters, e.g.:
    - `/get-leaf/spender/0x....`
    - `/get-left/earner/0x...`
  - [x] POST /v5/campaign/:id/close #417 (PR #457)
    (`newBudget = totalSpent`, i.e. `newBudget` = `oldBudget - remaining`)
  - [x] POST / PUT /v5/campaign (create / modify) #382
    - update spender available funds when they try to mutate campaigns
  - [x] GET `/v5/units-for-slot` #471 
  - [x] Enforce limits ( PR #413 )
  - [x] Events #382 ( PR #413 )
    - enforce per-campaign spending limits atomically - we already do this in `access`
  - [x] Distribute fees #381 ( PR #413 )
  - [x] Analytics breakdowns by 1hr #382 
  - [x] Campaign(s) remaining #415
- [x] Validator
  - [x] Worker flow #426 #433
     For details see JS issue https://github.com/AdExNetwork/adex-validator/issues/360
    - [x] worker will group the ticks (i.e. Accounting, NewState/ApproveState) per channel
    - [x] leader/follower ticks #428
    - [x] Channel tick #433 
    - [x] Tests @simzzz  #490 
  - [x] Unified precision #384 ( PR #386 #393 )
    - [x] Targeting rules DSL - use UnifiedNum instead of BigNum (part of #384)
  - [x] Remove Fees (and move to Sentry) #381 ( PR #413 )
  - [x] Outpace - spender & earner limits 
    - sum(spenders) = sum(earners) - use the `Balances<CheckedState>`. The struct can be directly deserialized and will check the state of the Balances.
    - For Spender - Deposit > spent (use the necessary sentry routes to perform this validation)
- [x] Adapter
  - [x] Calculate total spendable amount #380
- [x] Generic Deposit - instead of having adapter Deposit & spender Deposit, make the Deposit struct over a generic type ( impled in #432 )
- [ ] AdView manager:
  - [x] A way to test adview-manager generated code manually #476 #564 #566 
  - [x] Make V5 changes
  - [ ] Finalize #322 
```rust
pub struct Deposit<T> {
    pub total: T,
    pub still_on_create2: T,
}

impl Deposit<UnifiedNum> {
   pub fn from_precision(precision: u8, deposit: Deposit<BigNum>) -> Option<Deposit<UnifiedNum>> {... }
}
```
- [x] Remove `SpenderLeaf` #442 @simzzz 
- [ ] Integration tests - new mini test kit (see https://github.com/AdExNetwork/adex-validator/blob/v5/integrationTests.md) 
  - [x] PR #437 
    - [x] A `test_harness` crate for running the tests 
    - [x] A way to run 2 sentry servers (Leader / Follower)
  - [x] PR #454 
    - [x] A way to run both validator workers in single tick
    - [x] Writing the test cases #491 
  - [x] Analytics #494 

> deposit into a channel and create a campaign make sure it doesn't work before that submit events verify that payments appear in NewState/ApproveState, incl. fees verify that /analytics returns stuff

### Remove old V4 routes that are no longer needed:
- [x] Create Channel  `POST /channel` #435 
- [x] Validator Channel `POST /channel/validate` #435 
- [x] Status of Channel `GET /channel/:id/status` #435
- [x] Event aggregates `GET channel/:id/events-aggregates` (removed in #473)

### Sentry Authentication required (`AuthRequired` middleware) routes

- POST /v5/campaign (Auth is used to validate the campaign.creator)
- POST /v5/campaign/:id/close (Auth is used to validate the campaign.creator)
- POST /v5/channel/:id/spender/:addr
- GET /v5/channel/:id/spender/:addr
- POST /v5/channel/:id/spender/all
- GET channel/:id/events-aggregates (v4)
- POST channel/:id/validator-messages (v4)
- POST /v5/channel/:id/validator-messages
- /v5/channel/:id/pay
- /v5/analytics/for-publisher
- /v5/analytics/for-advertiser
- /v5/analytics/for-admin

**Comment by elpiel** [comment]
Here are a few questions and remarks on the current state of V5.
@Ivshti should take a look at the pending questions and we will discuss them together.

- `PAY` channel event (`POST /v5/channel/:id/pay`)
  - [x] how will this event be handled in analytics and accounting?
  - [x] How will this affect campaigns' remaining budget?
 - A `Channel` is created implicitly when creating a `Campaign` and we don't have a route for creating channels. Validate if the following statement is the desirable outcome: 
   - [x] `GET/POST /v5/channel/:id/spender/*` will all return `404` if there is no `Campaign` with the given `Channel.id`. Updating the Spendable amount (`POST /v5/channel/:id/spender/:addr`) will not be executable in this case until a `Campaign` is created with the given `Channel`.
 - On Campaign creation (`POST /v5/campaign`) in this case we perform:
   - [x] Channel insertion in DB (if it does not exist)
   - [x] Updating Spendable amount in the DB using the Adapter.
- [x] On Campaign modification (`POST /v5/campaign/:id`) **only** when the `budget` is modified we also update the Spendable amount in the DB using the Adapter.
- [x] How should we perform the `GET /v5/channel/:id/get-leaf`? Are these the correct steps to produce the given leaf:
   1. Generating a `MerkleTree` by getting the balance leaf of the spender/earner (see https://github.com/AmbireTech/adex-validator-stack-rust/blob/1bbb4e86a6797e80333c987abd784e623ebf8d06/adapter/src/lib.rs#L45-L70)
   2. making a `singable state root` for the `Channel` ( see https://github.com/AmbireTech/adex-validator-stack-rust/blob/1bbb4e86a6797e80333c987abd784e623ebf8d06/adapter/src/lib.rs#L28-L43)
   3. And finally hex encoding the result like we do with the `Channel` events
  - [x] What should happen if a request does not include a `spender` or `earner` query parameter?
  - 400
- [x] ~How should we be generating the SpenderLeaf merkle proof for `GET /v5/channel/:id/spender/:addr` & `GET /v5/channel/:id/spender/all`?~ We will drop this value from the response. API users will be forced to use `get-leaf`
- [x] ~Should we keep the current behavior on `GET /v5/campaign/list` query parameter - `isLeader`?~
  - ~`query.validator` is passed - filters `campaign.channel.leader = query.validator`~
  - ~no `query.validator` but is an authenticated call (we have `Bearer` auth token) - filter by `Campaign.channel.leader = Auth.uid`~
  - We will not keep this behavior. Instead use `validator=0x...` (for returning campaigns that have the validator as either leader or follower) & `leader=0x...` (returns only campaigns that the `Channel.leader = 0x...`)

**Comment by Ivshti** [comment]
- PAY event; the PAY event is outside the campaign, it is not associated with any campaign, and it affects `Accounting` directly without doing anything about the analytics; see "please note that we can't assume totalSpent equals the sum of all campaign spendings, because a spending can occur outside of campaign (cases like v4 CLOSE or PAY)"
- re non-existing channels, this behavior makes sense
- on campaign creation: makes sense
- when to update Spendable: also makes sense
- `get-leaf`: that's correct; if it doesn't conatin spender/earner, it's a 400 bad request
- sounds like the same procedure like `get-leaf` would be sufficient; actually, let's not return a leaf in this route for now, and force users to always call get-leaf
- this behavior is used by the validator when running through the campaigns to update them, so you decide whether to keep it depending on whether it's needed in the validator - I am pretty sure it is, so we'll need to keep it
