### ISSUE TITLE
AIP #61 v5: Channel and Campaign

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#382]
## [AIP AmbireTech/adex-validator-stack-rust#61](https://github.com/AdExNetwork/aips/issues/61)

Part of AmbireTech/adex-validator-stack-rust#377 

### Channel

As AIP#61 states the Channel is defined by `(leader, follower, guardian, tokenAddr, nonce)`

- Channel validation - is token allowed? is the requester a Leader or a Follower?
- No routes for storing Channels, they are gone.
- Only routes for listing all the channels (fetched by unique `channel_id` in the `campaigns` table)

### Campaign
- A Campaign is defined by `Campaign { id: CampaignId, channel: Channel, creator, validators, title.... rest of the ChannelSpec fields }`
  Note: The fields were aligned with Ivo before making the changes for the Campaign.
- `CampaignId` should be a randomly assigned value by `Sentry`, we've chosen the `Uuid` as a random generator in Rust and uses a representation of the 16 bytes as `0x` prefixed hex string

#### No migration

Apart from that, we can remove obsolete fields in the `ChannelSpec` (v4) as the v5 will not have migration from v4 as it will work in a different way than v4.

### Tasks:
- [x] v5 Campaign & Channel PRs AmbireTech/adex-validator-stack-rust#383, AmbireTech/adex-validator-stack-rust#388 (commit https://github.com/AdExNetwork/adex-validator-stack-rust/pull/388/commits/55616d4d6e4304d7c2672a1a25cd3d3206c07b23)
- [x] Campaign Validator AmbireTech/adex-validator-stack-rust#400 
- [x] Minimum token deposit & minimum validator fee AmbireTech/adex-validator-stack-rust#400 

**Sentry**
- [x] Database changes (migrations, queries, etc)
  - [x] Campaign DB table - PR AmbireTech/adex-validator-stack-rust#388 commit https://github.com/AdExNetwork/adex-validator-stack-rust/pull/388/commits/55616d4d6e4304d7c2672a1a25cd3d3206c07b23
  - [x] Other DB tables PR AmbireTech/adex-validator-stack-rust#388 commit https://github.com/AdExNetwork/adex-validator-stack-rust/pull/388/commits/55616d4d6e4304d7c2672a1a25cd3d3206c07b23
  - [x] Insert/Fetch Campaign AmbireTech/adex-validator-stack-rust#400 
  - [x] Accounting (1 row = 1 spender or earner)  AmbireTech/adex-validator-stack-rust#413 
  - [x] Channel DB table AmbireTech/adex-validator-stack-rust#432 

**Sentry routes**
- [x] Clean up V4 Channel and other routes & functions AmbireTech/adex-validator-stack-rust#435 
- [x] POST (create) `Campaign` AmbireTech/adex-validator-stack-rust#409 (PR AmbireTech/adex-validator-stack-rust#408 )
   - Should update `spendable` by calling the `adapter.get_deposit` and updating it in the DB
   - v4 Channel validations should be applied on the Campaign creation (i.e. token listed, minimum deposit, current `whoami` validator in the channel & campaign validators, etc.)
- [x] PUT (update) `Campaign`  AmbireTech/adex-validator-stack-rust#409 (PR AmbireTech/adex-validator-stack-rust#408 )
   - Should update `spendable` by calling the `adapter.get_deposit` and updating it in the DB
   - everything except `CampaignId` & `Campaign.channel` is mutable
   - Budget can changed in any direction (increase or decrease)
- [x] GET (list) Campaigns AmbireTech/adex-validator-stack-rust#429 (PR AmbireTech/adex-validator-stack-rust#430 )  @simzzz 
   See how we've done this for the V4 `GET /channel/list`
  - Query params:
    - `validator` - Address (not mandatory) OR
    - `leader` - Address  (not mandatory)
- [x] `adview-manager` update `POST ../events` route AmbireTech/adex-validator-stack-rust#466  @simzzz 

- [x] GET (list) Channel - V5 Tests #479 
   (In sentry) Use a separate `channels` table since we will need it for look-up when for example we want to get the last `ApproveState` we need to know now only the `Channel.id` (`/channel/:id/...` from the route) but also the `Channel.leader` to select the last approved `NewState` of the Leader (first to fetch the `ApproveState` and then to get the corresponding `NewState`)
- [x] POST /v5/campaign/events - insert new Event(s)
  - [x] Fees should be calculated when new Events are created AmbireTech/adex-validator-stack-rust#413 
  - [x] Spending limits should be enforced AmbireTech/adex-validator-stack-rust#413 
  - Move everything else in analytics - AnalyticsRecorder changes
 - Analytics V5
    - [x] Analytics AmbireTech/adex-validator-stack-rust#461 (JS https://github.com/AdExNetwork/adex-validator/blob/master/routes/analyticsV5.js)
    - [x] Recorder AmbireTech/adex-validator-stack-rust#449 (JS https://github.com/AdExNetwork/adex-validator/blob/master/services/sentry/analyticsRecorderV5.js)
    - [x] Additional tests for: AmbireTech/adex-validator-stack-rust#458 
    - `DateHour` (& FromSql & ToSql impls)
    - `sentry::analytics::record()` & `sentry::db::update_analytics` with more diverse Event & params of Events (like setting hostname, referrer, etc.)
