### ISSUE TITLE
AIP #61 v5: GET /channel/:id/spender/:addr

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#391]
## https://github.com/AdExNetwork/aips/issues/61

See the AIP#61 for up-to-date information.

### Tasks

- [x] `returns { totalDeposited, spenderLeaf }, where spenderLeaf will contain totalSpent and merkle proof` (from AIP#61)
  - `Accounting` & `NewState` include spender Balances, from which the `spenderLeaf` will be taken.
  - `spenderLeaf: (spender, balance)` however the request already contains the spender address, this is why we only need `totalSpent`
  - `merkle proof` of the **latest** `ApproveState`, this is so that we can validate that `spenderLeaf(hash("spender", spender, totalSpent))` is present in `latestApprovedState.stateRoot` (todo: additional clarifications needed)
 
- [x] `GET will return total spendable amount (from Spendable in the DB) and spender leaf` (from AIP#61)
- [x] Update NewState & ApproveState with the new `Balances::<CheckedState>` once merged #422 #423
- [x] ~Generate MerkleProof in the `SpenderLeaf`~ https://github.com/AdExNetwork/adex-validator-stack-rust/issues/377#issuecomment-933280214
