### ISSUE TITLE
AIP #61 v5: GET /channel/:id/spender/all

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#392]
## https://github.com/AdExNetwork/aips/issues/61

Related to #391 as this should return all spenders limits 

- [x] Route impl #424 
- [x] Pagination of response #441

**Comment by elpiel** [comment]
There are a few tests that still need to be done for the pagination. Please refer to this PR comment:

https://github.com/AdExNetwork/adex-validator-stack-rust/pull/441#pullrequestreview-768975401

**Comment by elpiel** [comment]
### TODOs
- [x] `validator_worker::sentry_interface::SentryApi::get_all_spenders` to use the paginated responses #451 

(from https://github.com/AmbireTech/adex-validator-stack-rust/pull/441#pullrequestreview-768975401):

Make sure to make test that covers:
- 0 records
- less than 1 page of records
- 2 pages of records

This way we can test if queries are correct and returning the expected results

Make sure to write tests for the pagination in Sentry to:
- [x] Check page count #451 
- [x] Check ordering & Records  #451
