### ISSUE TITLE
AIP #61 v5: NewState and Accounting

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#398]
### Sentry 

`NewState` and `Accounting` should contain 2 balances maps (for earners and spenders) and we need to be able to distinguish between them:
- balances - earners map
- balancesSpenders - spenders map

**IMPORTANT:** Although there is division in 2 maps of the balances, the `state_root` should contain both (i.e. the should be merged into a single tree)

balancesSpenders - in order to avoid duplication when merging the two maps, `spenderLeaf`s should be hashed by `hash("spender", spender, totalSpent)` (notice the string slice included when hashing to create a different hash than the earners map)

`Accounting`:
 - [x] Used to create `NewState` & `ApproveState` #428 
 - [x] Filled by the flat `sentry::db::Accounting` for a given `Channel` #439 
 - [x] MerkleTree should use actual precision of the token (e.g. DAI - 18, USDT - 6, etc.) #426
