### ISSUE TITLE
Additional tests

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#540]
While working on #535 I realized that we are missing tests for exiting routes and/or middlewares.
We should cover these portions of the code and also add tests for the axum routes to make sure middlewares and paths are correctly applied and matched.

NOTE: These were all tested manually when rewriting to `axum`

### TODOs:

Routes:

- [x] GET /v5/channel/:id/validator-messages (`/` | `/:address` | `/:address/:message_types` ) @elpiel #556 
- [x] POST /v5/channel/:id/validator-messages @simzzz  #549 
- [x] GET /v5/analytics/(for-publisher, for-advertiser, for-admin) @simzzz #549 

Middlewares:

- [x] authenticate_as_advertiser @elpiel #546 
- [x] authenticate_as_publisher @elpiel #546 
- [x] is_admin @elpiel #546 
- [x] channel_load (with multiple params too) @elpiel #546 
- [x] campaign_load (add test with multiple params as well) @elpiel #546 
- [x] called_by_creator @elpiel #546 

Other improvements:
- [x] Message types filtering deserializatoin for `GET /v5/channel/:id/validator-messages/:addr/:message_types` @elpiel #547
