### ISSUE TITLE
Unify prices to be per 1 instead of per 1000 (pro mille)

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#563]
We have many places where a UnifedNum price is mentioned and some of them don't mention if they are per 1 or per 1000.

We are looking to unify all prices in the validator to be per 1 and this is a list of most of the places that need unification:

- [x] - ValidatorDesc fee (the validator payout should be calculated per 1, right now it's per 1000)
- [x] - Targeting - event price
- [x] - Campaign  - Pricing bounds
- [x] - AdView manager - NextAdUnit price
- [x] - units-for-slot - UnitsWithPrice
- [x] - Config limits - units for slot - global_min_impression_price

## Tasks:
- [x] Change and document all prices in the systems from the list above to be per 1 event.
- [x] Research and change (if any) other places that need changing as well.
