### ISSUE TITLE
Configuration file limits and timeouts sepratation

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#565]
The main goal of this issue is to separate and organise the configuration values.

Since the `/units-for-slot` route we have a struct `Limits` section in the configuration which should be further extend with other values.
It makes sense to separate them in such a way that we don't create multiple structs with 1 or 2 fields but also logically separate them.

A good first step would be to distinguish the values used only in sentry or only in validator and proceed with the separation from there on.

# Tasks
- [x] Figure out a good way to combine and separate the given timeouts, limits and other configuration values
- [x] Separate config values
- [x] Update both `ganache.toml` & `prod.toml`
- [x] Update `GET /cfg` response example (primitives)
