### ISSUE TITLE
Remaining TODO's in the code 

### ISSUE THREAD

**Issue by simzzz** [AdExNetwork/adex-validator-stack-rust#570]
### Adapter

- [x] `ethereum/client.rs` - We return an `EwtSigningError` when the wallet sign fails in the `sign()` function even though we do not sign an Ethereum Web Token but an Outpace state_root
- [x] `ethereum/ewt.rs` - Determine if it's necessary to replace the error in the `base64_decode()` function for the `Payload` struct with our own instead of `EwtVerifyError`

### Ad-view Manager

- [x] - `serve/src/routes.rs` -  Check if the `navigator_language` value in the options is correct
- [x] - `helpers.rs` - Check if the quotes in the `fetch_opts` variable are correct
_Done in #564_

- [x] - `manager.rs` - Check what should happen if no validators are found in `get_next_adunit()` for the campaign
_Checked this while working on #566 , there should always be a validator_

- [x] - `manager.rs` - Check if there is a scenario in production where the `units_with_price` for a campaign can be modified

### Config

~~`ganache.toml` - Check the POST /validator-message route performance, more than 1 second for timeout is a lot!~~

### Primitives

~~`analytics/query.rs` - Make the `start` field in the `Time` struct either a timestamp or `DateTime` string when serializing/deserializing~~
_Mentioned in #493, currently low priority_
- [x] - `targeting/input/field.rs` - `Balances` enum should drop `PublisherEarnedFromCampaign` value 
- [x] - `targeting/eval.rs` - Check the issue linked above the `Function` enum
- [x] - `lib.rs` - Remove `allow(unstable_name_collisions)` once num::Integer::div_floor() is fixed
- [x] - `unified_num.rs` - Check math and write tests for the `mod_floor()`, `gcd()`, `lcm()`, `divides()`, `is_multiple_of(), and `div_rem()` functions
_.divides() is deprecated, should we keep it implemented?_
- [x] - `cargo.toml` - Change ChannelId Serialize implementation in order to remove `serde-hex`
_How should we serialize it instead?_

### Sentry

- [x] - `db/analytics.rs` - throw a few more analytics in specific DateHours w/ unique Query and check if it filters the analytics correctly in the `test_get_analytics_in_december()` test
- [x] - `db/campaign.rs` - Check and update the statement in `fetch_campaign()`

~~#571~~
_Needs more research, exporting to a separate issue_

~~`db.rs` - Fix error mapping in the `create()` function of the `Manager`~~

### Validator Worker
- [x] - `error.rs` - Add channel, validatorId etc. for the `ChannelNotIntendedForUs` Error variant in the enum
~~`follower.rs` - Check if we should use the health value when displaying `InvalidNewState`~~
- [x]  - `follower.rs` - Context for All spender sum Error when overflow occurs in the follower tick
~~`follower.rs` - Should we show the Payout Mismatch between Spent & Earned in `on_new_state()`~~
- [x] - `follower.rs` - Add context for `proposed_balances.check()` overflow error
- [x] - `follower.rs` - Add context for Transition error
- [x] - `follower.rs` - Add context for error in Spenders and Earners transition
- [x] - `lib.rs` - Double check `get_state_root_hash_returns_correct_hash` test
_How should the encoded value be checked?_
