### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#7]
Figure out how to error handle on the different layers of the Sentry application.
A good abstraction over the errors might be something like this:

https://github.com/elpiel/rest-api-error-handling

Having an `ApplicationError` that is an enum and contains the different places where error can occur. Places as in Persistence layer, Domain and Validation errors and etc.

- [x] Persistence Error handling #12 
- [ ] Persistence `UserError` and handling #14 
- [ ] Tower-web Deserialization/Validation error handling
- [ ] TODO: more the come

Major drawback from tower-web:
https://github.com/carllerche/tower-web/issues/86#issuecomment-447957198

> Looks like they aren't documented :-1: Also, the impl is not complete. The error is not passed to the handler yet :( (probably why it isn't documented yet).

And I couldn't make it work with `async fn`, although I didn't spend much time on it, but it was generating error in the `impl_web` macro.

**Comment by elpiel** [comment]
This issue is irrelevant after the refactor
