### ISSUE TITLE
API requests

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#9]
### Channel:

- [x] GET /channel/list #203 
- [x] GET /channel/:id/status #198 
- [x] GET /channel/:id/validator-messages/:uid?/:type? #207 
- [x] GET /channel/:id/events-aggregates/ @elpiel @samparsky #229 & #237 & #239
- [x] ~~GET /channel/:id/events-aggregates/:earner~~
- [x] GET /channel/:id/last-approved
- [x] ~~GET /channel/:id/tree~~
- [x] POST /channel #198 
- [x] ~~POST /channel/validate~~
- [x] POST /channel/:id/validator-messages @samparsky  #246 
- [x] POST /channel/:id/events @samparsky #239 
- [x] ~~POST /channel/:id/events/close ( No JS reference )~~

### Other:
- [x] GET /analytics #209 
- [x] GET /analytics/:id #209 
- [x] GET /cfg #170

**Comment by elpiel** [comment]
All the routes seem to be implemented. Any further changes/routes should have their own separate issues, now that the main part is done.
Closing this issue :tada:
